apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: test2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sc2
    spec:
      containers:
      - name: dock0
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        dependsOn:
          - dock1
      - name: dock1
        image: nginx:1.7.9
        

